on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - id: foo
      uses: zvnlanx/hello-world-compposite-run-steps-action@v1
      with:
        who-to-greet: "zvnlanx"
    - run: echo random-number ${{ steps.foo.outputs.random-number }}
      shell: bash
